#!/usr/bin/env python3
"""
close-session.py — End-of-session state capture.

1. Reads today's game session JSONL(s) for the player's Telegram channel
2. Extracts narrative exchanges (player + Labyrinth), filters out cron/system noise
3. Saves a clean daily transcript to logs/transcripts/YYYY-MM-DD.md
4. Loads structured events — either from --events-file (preferred, generated by the
   Labyrinth itself) or by calling the default Openclaw agent on the transcript
5. Cascades those events to state files:
     - memory/diary/YYYY-MM-DD.md     (appends session summary if not already written)
     - memory/arc-spine.md            (last session, what story is ready for)
     - lore/nothing-intelligence.md   (pressure, confrontations, strategy update)
     - players/[name].md              (belief, investments, inventory, relationships)

## How the Labyrinth should call this

The Labyrinth runs this at session close, from within the running session. Because the
session is locked, it cannot call `openclaw agent --local` for extraction. Instead,
the Labyrinth generates the events JSON itself and passes it in:

  1. Labyrinth generates a JSON object matching the schema below
  2. Writes it to /tmp/enchantify-events.json
  3. Calls: python3 scripts/close-session.py --player bj \\
               --session-file ~/.openclaw/agents/enchantify/sessions/<current>.jsonl \\
               --events-file /tmp/enchantify-events.json

## Events JSON schema

{
  "belief_final": 81,                  // player Belief at session end, or null
  "belief_changes": [                  // every Belief gain/loss
    {"amount": 3, "reason": "..."}
  ],
  "belief_investments": [              // Belief permanently invested somewhere
    {"target": "Zara Finch", "type": "npc", "amount": 10, "notes": "..."}
  ],
  "nothing_events": [                  // confrontations, manifestations, retreats
    {"type": "confrontation", "date": "2026-04-17",
     "location": "North Gardens", "outcome": "overwritten", "details": "..."}
  ],
  "enchantments_cast": [
    {"name": "Everything Speaks", "target": "table lager", "outcome": "..."}
  ],
  "npc_interactions": [                // only if relationship score changed
    {"npc": "Zara Finch", "relationship_delta": 5, "notes": "..."}
  ],
  "inventory_changes": [
    {"action": "gained", "item": "black envelope", "notes": "left by Nothing"}
  ],
  "fae_bargains": [],
  "quests_completed": [],
  "quests_added": [],
  "compass_runs_completed": 0,         // integer — Compass Runs fully completed this session
  "session_summary": "...",            // 2-3 sentence narrative summary
  "most_alive_moment": "...",          // most vivid real moment
  "what_fell_flat": null,              // or string
  "thread_updates": [                  // threads touched this session
    {
      "name": "Wicker's Campaign",     // must match world-register Active Threads name exactly
      "phase": "rising",               // current phase word
      "status": "crew has gone quiet; something is being planned involving the exhibition",
      "next_beat": "His crew has been quieter than usual..."  // optional; omit if unchanged
    }
  ],
  "new_threads": [                     // newly confirmed subplots from play or THREAD SEED
    {
      "name": "Orion's Missing Office",
      "id": "orion-missing-office",
      "type": "npc-subplot",
      "phase": "setup",
      "pressure": "low",
      "npc_anchor": "Headmaster Orion Blackthorn",
      "locations": "Headmaster's Office, Great Hall",
      "entities": "Headmaster Orion Blackthorn",
      "nothing_pressure": "medium - absence would love to make authority feel hollow",
      "status": "Orion has begun leaving contradictory office hours in the margins",
      "next_beat": "A student finds two official notices from Orion that cannot both be true.",
      "starting_belief": 7
    }
  ]
}

## Standalone usage (no running session, --events-file not needed)

  python3 scripts/close-session.py                            # today, auto-detect session
  python3 scripts/close-session.py --player bj --date 2026-04-17
  python3 scripts/close-session.py --session-file /path/to/session.jsonl
  python3 scripts/close-session.py --transcript-only         # transcript only, no events
  python3 scripts/close-session.py --dry-run                 # no file writes
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from scene_ledger import load_entries as load_scene_ledger_entries
from thread_sync import sync_thread_files

BASE        = Path(__file__).parent.parent
SESSIONS_F  = Path.home() / ".openclaw" / "agents" / "enchantify" / "sessions" / "sessions.json"
SESSIONS_D  = SESSIONS_F.parent
OPENCLAW_BIN = shutil.which("openclaw") or "/opt/homebrew/bin/openclaw" or "/usr/local/bin/openclaw"
NARRATIVE_STEWARD_STATE = BASE / "config" / "narrative-steward-state.json"

# Local timezone — used for grouping messages by "day"
LOCAL_TZ = ZoneInfo("America/New_York")

# Channel keys that represent actual player game sessions (not cron, not openai test)
PLAYER_CHANNEL_PATTERNS = [
    "agent:enchantify:telegram:direct:",
    "agent:enchantify:main",
]


# ── Parsing helpers ────────────────────────────────────────────────────────────

def parse_player_text(raw: str):
    """
    Extract the actual player-typed text from a user message.

    Player messages from Telegram come wrapped in a 'Conversation info' JSON block.
    Bare messages (from /slash commands or direct injection) are returned as-is
    after filtering out system-only content.
    Returns str or None.
    """
    if raw.startswith("System:"):
        return None
    if raw.startswith("[cron:"):
        return None
    if raw.startswith("--- SESSION ENTRY"):
        return None

    # Telegram wrapper: "Conversation info (untrusted metadata):\n```json\n...\n```\n\nSender...\n\nACTUAL TEXT"
    m = re.search(r'Sender \(untrusted[^\n]*\)\s*\n+(.*)', raw, re.DOTALL)
    if m:
        text = m.group(1).strip()
        if not text or text.startswith("[plugins]"):
            return None
        return text

    # Media-only message with no text
    if raw.startswith("[media attached:") and "\n" not in raw.strip():
        return "[image shared]"

    # Bare message (no Telegram wrapper) — only accept if short and not a system prompt
    stripped = raw.strip()
    system_prefixes = (
        "You are the Labyrinth", "HEARTBEAT", "---\n", "Context about",
        "--- SESSION", "DIRECTIVE:", "[cron", "System:", "# Tick",
        "PLAYER:", "AWAY_HOURS:", "TODAY:", "BASE PATH:",
    )
    if any(stripped.startswith(p) for p in system_prefixes):
        return None
    if len(stripped) > 300:
        return None
    if len(stripped) < 2:
        return None
    return stripped


def parse_labyrinth_text(content):
    """Extract the visible narrative text from an assistant message."""
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        parts = []
        for c in content:
            if isinstance(c, dict) and c.get("type") == "text":
                parts.append(c["text"])
        text = "\n".join(parts)
    else:
        return None

    # Strip <think>...</think> blocks (internal reasoning)
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

    # Unwrap <final>...</final>
    m = re.search(r'<final>(.*?)</final>', text, re.DOTALL)
    if m:
        text = m.group(1).strip()

    # Filter pure system messages
    if text.startswith("✅ New session started"):
        return None
    if text == "NO_REPLY" or not text:
        return None
    if len(text) < 10:
        return None

    return text


def load_session_messages(session_file: Path) -> list[dict]:
    """Parse a JSONL session file, return list of {ts, role, text} dicts."""
    messages = []
    if not session_file.exists():
        return messages

    with open(session_file) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            if obj.get("type") != "message":
                continue

            msg   = obj.get("message", {})
            role  = msg.get("role", "")
            ts_s  = obj.get("timestamp", "")
            content = msg.get("content", "")

            if not role or not ts_s:
                continue

            try:
                ts = datetime.fromisoformat(ts_s.replace("Z", "+00:00"))
            except ValueError:
                continue

            if role == "user":
                raw = content[0]["text"] if isinstance(content, list) and content else str(content)
                text = parse_player_text(raw)
                if text:
                    messages.append({"ts": ts, "role": "player", "text": text})

            elif role == "assistant":
                text = parse_labyrinth_text(content)
                if text:
                    messages.append({"ts": ts, "role": "labyrinth", "text": text})

    return messages


def find_player_session_files() -> list[Path]:
    """Return session file paths for all player-facing channels, most recent first."""
    if not SESSIONS_F.exists():
        return []

    with open(SESSIONS_F) as f:
        sessions = json.load(f)

    files = []
    for key, val in sessions.items():
        if any(key.startswith(p) for p in PLAYER_CHANNEL_PATTERNS):
            sf = val.get("sessionFile", "")
            if sf:
                p = Path(sf)
                if p.exists():
                    files.append(p)

    # Deduplicate, sort newest first by mtime
    seen = set()
    unique = []
    for p in sorted(set(files), key=lambda x: x.stat().st_mtime, reverse=True):
        if p not in seen:
            seen.add(p)
            unique.append(p)

    return unique


def build_daily_transcript(target_date: str) -> list[dict]:
    """
    Collect all narrative messages from target_date (YYYY-MM-DD, local time).
    Searches across session files — a single session can span midnight.
    """
    target = datetime.strptime(target_date, "%Y-%m-%d").date()
    all_messages = []

    session_files = find_player_session_files()
    # Also scan recent session files that aren't indexed (e.g. after context reset)
    for p in sorted(SESSIONS_D.glob("*.jsonl"), key=lambda x: x.stat().st_mtime, reverse=True)[:20]:
        if p not in session_files:
            session_files.append(p)

    seen_texts = set()
    for sf in session_files:
        for msg in load_session_messages(sf):
            local_date = msg["ts"].astimezone(LOCAL_TZ).date()
            if local_date == target:
                key = (msg["role"], msg["text"][:80])
                if key not in seen_texts:
                    seen_texts.add(key)
                    all_messages.append(msg)

    all_messages.sort(key=lambda m: m["ts"])
    return all_messages


def format_transcript(messages: list[dict], date: str) -> str:
    """Render messages as a readable markdown transcript."""
    lines = [f"# Session Transcript — {date}\n"]
    prev_date = None

    for msg in messages:
        local_ts = msg["ts"].astimezone(LOCAL_TZ)
        day_str = local_ts.strftime("%A, %B %-d")
        if day_str != prev_date:
            lines.append(f"\n---\n*{day_str}*\n")
            prev_date = day_str

        time_str = local_ts.strftime("%-I:%M %p")
        label = "**bj**" if msg["role"] == "player" else "*The Labyrinth*"
        text = msg["text"].strip()
        lines.append(f"[{time_str}] {label}: {text}\n")

    return "\n".join(lines)


# ── LLM extraction ─────────────────────────────────────────────────────────────

EXTRACTION_PROMPT_TEMPLATE = """You are the Enchantify state-capture system. Read the session transcript below and extract structured events.

Return ONLY a valid JSON object — no markdown, no commentary, no code block. If a field has nothing to report, use an empty array or null.

Extract:
- belief_final: the player's Belief score at session end (integer, or null if unclear)
- belief_changes: list of {{amount, reason}} — every Belief gain/loss mentioned
- belief_investments: list of {{target, type, amount, notes}} where type is "anchor", "npc", "location", or "object"
- nothing_events: list of {{type, date, location, outcome, details}} — confrontations, manifestations, retreats
- enchantments_cast: list of {{name, target, outcome}}
- npc_interactions: list of {{npc, relationship_delta, notes}} — only if relationship changed
- inventory_changes: list of {{action, item, notes}} where action is "gained" or "lost"
- fae_bargains: list of {{fae, gave, owes, deadline}}
- quests_completed: list of quest NPC names
- quests_added: list of {{npc, description}}
- session_summary: 2-3 sentence summary of what happened narratively
- most_alive_moment: the single most vivid/real moment from the session (quoted or described)
- what_fell_flat: anything that felt mechanical, flat, or broke immersion (or null)
- notable_objects: any objects that appeared, changed, or were left behind (the black envelope, etc.)

SESSION DATE: {date}
PLAYER: {player}

TRANSCRIPT:
{transcript}"""


def call_openclaw(prompt: str, timeout: int = 180) -> str:
    """Call the default Openclaw agent and return its text output."""
    result = subprocess.run(
        [OPENCLAW_BIN, "agent", "--local", "--agent", "enchantify", "-m", prompt],
        capture_output=True, text=True, timeout=timeout
    )
    output = result.stdout.strip()
    # Strip ANSI escape codes and noise lines
    output = re.sub(r'\x1b\[[0-9;]*m', '', output)
    noise = ("[plugins]", "[agents/", "[agent/", "adopted ", "google tool", "✅ New session")
    clean = [line for line in output.splitlines() if not any(line.strip().startswith(n) for n in noise)]
    return "\n".join(clean).strip()


def extract_events(transcript_text: str, date: str, player: str):
    """Send transcript to the default agent and parse structured event JSON."""
    # Trim transcript if very long — keep first + last portions for context
    max_chars = 12000
    if len(transcript_text) > max_chars:
        half = max_chars // 2
        transcript_text = transcript_text[:half] + "\n\n[... middle trimmed for length ...]\n\n" + transcript_text[-half:]

    prompt = EXTRACTION_PROMPT_TEMPLATE.format(
        date=date, player=player, transcript=transcript_text
    )

    print("  → Calling default Openclaw agent for event extraction…")
    raw = call_openclaw(prompt)

    # Find JSON in the response
    json_match = re.search(r'\{.*\}', raw, re.DOTALL)
    if not json_match:
        print(f"  ✗ No JSON found in agent response. Raw output:\n{raw[:500]}")
        return None

    try:
        return json.loads(json_match.group(0))
    except json.JSONDecodeError as e:
        print(f"  ✗ JSON parse error: {e}\nRaw: {raw[:500]}")
        return None


EVENT_LIST_FIELDS = [
    "belief_changes",
    "belief_investments",
    "nothing_events",
    "enchantments_cast",
    "npc_interactions",
    "inventory_changes",
    "fae_bargains",
    "quests_completed",
    "quests_added",
    "thread_updates",
    "new_threads",
]


def validate_events(events: dict) -> list[str]:
    """Return closeout event schema/quality problems."""
    problems = []
    if not isinstance(events, dict):
        return ["events root must be a JSON object"]

    summary = str(events.get("session_summary") or "").strip()
    if len(summary) < 40:
        problems.append("session_summary is missing or too short")

    if "belief_final" in events and events.get("belief_final") is not None and not isinstance(events.get("belief_final"), int):
        problems.append("belief_final must be an integer or null")

    for field in EVENT_LIST_FIELDS:
        if field in events and events.get(field) is not None and not isinstance(events.get(field), list):
            problems.append(f"{field} must be a list")

    for idx, item in enumerate(events.get("belief_changes") or []):
        if not isinstance(item, dict) or not isinstance(item.get("amount"), int) or not item.get("reason"):
            problems.append(f"belief_changes[{idx}] needs integer amount and reason")

    for idx, item in enumerate(events.get("belief_investments") or []):
        if not isinstance(item, dict) or not item.get("target") or not item.get("type"):
            problems.append(f"belief_investments[{idx}] needs target and type")
        amount = item.get("amount")
        if amount is not None and amount != "TBC" and not isinstance(amount, int):
            problems.append(f"belief_investments[{idx}].amount must be integer, TBC, or null")

    for idx, item in enumerate(events.get("nothing_events") or []):
        if not isinstance(item, dict) or not item.get("type") or not item.get("details"):
            problems.append(f"nothing_events[{idx}] needs type and details")

    completed_count = events.get("compass_runs_completed", 0)
    if completed_count is None:
        completed_count = 0
    if not isinstance(completed_count, int):
        problems.append("compass_runs_completed must be an integer")
    elif completed_count > 0 and not events.get("compass_run_details"):
        problems.append("compass_runs_completed > 0 requires compass_run_details")

    for idx, item in enumerate(events.get("thread_updates") or []):
        if not isinstance(item, dict) or not item.get("name") or not item.get("phase") or not item.get("status"):
            problems.append(f"thread_updates[{idx}] needs name, phase, and status")

    for idx, item in enumerate(events.get("new_threads") or []):
        required = ("name", "id", "phase", "status", "next_beat", "npc_anchor")
        if not isinstance(item, dict) or any(not item.get(key) for key in required):
            problems.append(f"new_threads[{idx}] needs " + ", ".join(required))
            continue
        belief = item.get("starting_belief", 7)
        if not isinstance(belief, int) or belief < 1 or belief > 20:
            problems.append(f"new_threads[{idx}].starting_belief must be an integer from 1 to 20")

    return problems


# ── State file updaters ──────��─────────────────────────────────────────────────

def read_file(path: Path) -> str:
    return path.read_text() if path.exists() else ""


def write_file(path: Path, content: str, dry_run: bool = False):
    if dry_run:
        print(f"  [dry-run] Would write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  ✓ Updated {path.relative_to(BASE)}")


def update_diary(events: dict, date: str, player: str, dry_run: bool):
    diary_path = BASE / "memory" / "diary" / f"{date}.md"
    summary = events.get("session_summary", "").strip()
    alive   = events.get("most_alive_moment", "").strip()
    flat    = events.get("what_fell_flat", "")

    if not summary:
        return

    existing = read_file(diary_path)

    # Don't duplicate if summary already appears in the file
    if summary[:60] in existing:
        print(f"  · Diary already contains today's summary — skipping")
        return

    entry_parts = [f"## Session {date}\n", summary]
    if alive:
        entry_parts.append(f"\n*Most alive:* {alive}")
    if flat and flat.lower() not in ("null", "none", ""):
        entry_parts.append(f"\n*What fell flat:* {flat}")

    entry = "\n".join(entry_parts)

    if existing.strip():
        new_content = existing.rstrip() + "\n\n---\n\n" + entry + "\n"
    else:
        new_content = f"# Labyrinth Diary — {date}\n*Player: {player}*\n\n" + entry + "\n"

    write_file(diary_path, new_content, dry_run)


def update_arc_spine(events: dict, date: str, dry_run: bool):
    spine_path = BASE / "memory" / "arc-spine.md"
    content = read_file(spine_path)
    summary = events.get("session_summary", "").strip()
    scene_ledger = events.get("scene_ledger", {})

    if not summary:
        return

    if scene_ledger.get("titles"):
        summary = summary.rstrip() + f"\n\nRecent scene titles: {', '.join(scene_ledger.get('titles', [])[-3:])}."

    # Update belief state line if we have a final belief
    belief_final = events.get("belief_final")
    if belief_final and isinstance(belief_final, int):
        content = re.sub(
            r'(- Belief:\s*)\d+(\s*[—-])',
            lambda m: f"{m.group(1)}{belief_final}{m.group(2)}",
            content
        )

    # Replace Last Session block
    new_session_block = f"## Last Session\n*{date}*\n\n{summary[:400]}"
    if re.search(r'^## Last Session', content, re.MULTILINE):
        content = re.sub(
            r'## Last Session\s*\n.*?(?=\n##|\Z)',
            new_session_block + "\n",
            content,
            flags=re.DOTALL
        )
    else:
        content = content.rstrip() + "\n\n" + new_session_block + "\n"

    write_file(spine_path, content, dry_run)


def update_nothing_intelligence(events: dict, date: str, dry_run: bool):
    path = BASE / "lore" / "nothing-intelligence.md"
    content = read_file(path)
    nothing_events = events.get("nothing_events", [])
    if not nothing_events:
        return

    confrontations = [e for e in nothing_events if e.get("type") in ("confrontation", "overwrite", "defeat")]
    if not confrontations:
        return

    c = confrontations[-1]
    event_date     = c.get("date", date)
    location       = c.get("location", "unknown location")
    outcome        = c.get("outcome", "outcome unknown")
    details        = c.get("details", "")

    # Update pressure level
    content = re.sub(r'(Pressure level:\s*).*', r'\1retreating', content)

    # Update Updated date
    content = re.sub(r'(\*Updated:\s*)[\d-]+', rf'\g<1>{date}', content)

    # Append to Recent Activity
    new_activity = f"- **{event_date}:** {details or f'Confronted and {outcome} at {location}. Retreated.'}"
    if "## Recent Nothing Activity" in content:
        content = content.rstrip() + f"\n{new_activity}\n"
    else:
        content += f"\n\n## Recent Nothing Activity (from diary)\n{new_activity}\n"

    write_file(path, content, dry_run)


def update_player_file(events: dict, player: str, dry_run: bool):
    path = BASE / "players" / f"{player}.md"
    content = read_file(path)

    # Update Belief score
    belief_final = events.get("belief_final")
    if belief_final and isinstance(belief_final, int):
        content = re.sub(
            r'(- \*\*Belief:\*\*\s*)\d+',
            rf'\g<1>{belief_final}',
            content
        )

    # Add new Belief investments to the table
    investments = events.get("belief_investments", [])
    for inv in investments:
        target = inv.get("target", "?")
        inv_type = inv.get("type", "?")
        amount = inv.get("amount", "TBC")
        notes = inv.get("notes", "")

        # Check if already in the table
        if target.lower() in content.lower() and "Belief Investments" in content:
            continue

        new_row = f"| {target} | {inv_type.title()} | {amount} | {notes} |"

        if re.search(r'## Belief Investments\s*\n\s*\|', content):
            # Append to existing table
            content = re.sub(
                r'(## Belief Investments\s*\n(?:\|[^\n]+\n)+)',
                lambda m: m.group(0).rstrip() + f"\n{new_row}\n",
                content
            )
        else:
            # Replace the empty placeholder
            new_table = (
                "## Belief Investments\n\n"
                "| Target | Type | Belief | Notes |\n"
                "|---|---|---|---|\n"
                f"{new_row}\n"
            )
            content = re.sub(
                r'## Belief Investments\s*\n\n\*\(Nothing invested.*?\)\*',
                new_table.rstrip(),
                content,
                flags=re.DOTALL
            )

    # Update relationship scores
    for interaction in events.get("npc_interactions", []):
        npc   = interaction.get("npc", "")
        delta = interaction.get("relationship_delta", 0)
        if not npc or not delta:
            continue
        # Find existing row in Relationships table
        m = re.search(
            rf'(\|\s*{re.escape(npc)}\s*\|[^|]*\|\s*)(\d+)(\s*\|)',
            content
        )
        if m:
            new_score = int(m.group(2)) + int(delta)
            content = content[:m.start()] + m.group(1) + str(new_score) + m.group(3) + content[m.end():]

    write_file(path, content, dry_run)


def update_labyrinth_state_from_events(events: dict, dry_run: bool):
    scene_ledger = events.get("scene_ledger", {})
    if not scene_ledger:
        return

    state_path = BASE / "memory" / "labyrinth-state.md"
    content = read_file(state_path)
    if not content:
        return

    titles = scene_ledger.get("titles", [])[-3:]
    failures = scene_ledger.get("delivery_failures", [])
    latest_text = (scene_ledger.get("latest_text") or "").strip()

    watching = []
    if titles:
        watching.append("Recent realized scenes: " + ", ".join(titles))
    if latest_text:
        watching.append("Latest delivered scene texture: " + latest_text[:220])
    if failures:
        watching.append("Delivery weak points observed: " + "; ".join((f.get("title") or f.get("scene_id") or "scene") for f in failures[:3]))
    if not watching:
        return

    new_block = "\n".join(f"- {line}" for line in watching)
    content = re.sub(
        r'(## What It\'s Watching\n)([\s\S]*?)(?=\n## |\Z)',
        lambda m: m.group(1) + "\n" + new_block + "\n",
        content,
    )
    write_file(state_path, content, dry_run)


def scene_ledger_digest(date: str) -> dict:
    entries = load_scene_ledger_entries(date)
    if not entries:
        return {"entries": [], "scene_ids": [], "titles": [], "delivery_failures": [], "latest_text": ""}

    scene_ids = []
    titles = []
    delivery_failures = []
    latest_text = ""
    for entry in entries:
        scene_id = entry.get("scene_id")
        title = entry.get("title")
        if scene_id:
            scene_ids.append(scene_id)
        if title:
            titles.append(title)
        if entry.get("delivery_ok") is False or entry.get("essential_ok") is False:
            delivery_failures.append({
                "scene_id": scene_id,
                "title": title,
                "essential_ok": entry.get("essential_ok"),
                "delivery_ok": entry.get("delivery_ok"),
            })
        if entry.get("text"):
            latest_text = entry.get("text")
    return {
        "entries": entries,
        "scene_ids": scene_ids,
        "titles": titles,
        "delivery_failures": delivery_failures,
        "latest_text": latest_text,
    }


# ── Thread state updaters ─────────────────────────────────────────────────────

THREADS_MD   = BASE / "lore" / "threads.md"
REGISTER_MD  = BASE / "lore" / "world-register.md"


def update_thread_in_register(name: str, phase: str, status: str, dry_run: bool):
    """Update the Notes column for a thread row in world-register.md Active Threads."""
    result = sync_thread_files(name, phase=phase, status=status, dry_run=dry_run)
    if not result.get("register_changed"):
        print(f"  · Thread '{name}' not found in world-register Active Threads — skipping register update")


def update_thread_in_threads_md(name: str, phase: str, next_beat: str, dry_run: bool):
    """Update **phase:** and optionally **Next beat:** in the threads.md section."""
    from datetime import date as _date
    last_advanced = _date.today().isoformat() if next_beat else None
    result = sync_thread_files(name, phase=phase, next_beat=next_beat, last_advanced=last_advanced, dry_run=dry_run)
    if not result.get("threads_changed"):
        print(f"  · Thread '{name}' not found in threads.md — skipping threads.md update")


def print_thread_checklist():
    """Print current thread states as a close-session reminder when no updates were provided."""
    content = read_file(REGISTER_MD)
    active_m = re.search(r'(?m)^## Active Threads\s*\n(.*?)(?=^## |\Z)', content, re.DOTALL)
    if not active_m:
        return

    threads = []
    for m in re.finditer(
        r'^\|\s*([^|]+?)\s*\|\s*Thread\s*\|\s*(\d+)\s*\|\s*([^|]*)\s*\|',
        active_m.group(1), re.MULTILINE | re.IGNORECASE
    ):
        name  = m.group(1).strip()
        bel   = m.group(2)
        notes = m.group(3).strip()
        pm = re.search(r'Phase:\s*(\w+)(?:[^—\n]*—\s*(.+))?', notes, re.IGNORECASE)
        phase  = pm.group(1) if pm else '?'
        status = (pm.group(2) or '').strip().rstrip(';') if pm else notes
        threads.append((name, bel, phase, status))

    if not threads:
        return

    print("\n  ┌─ Thread checklist (update world-register Notes + threads.md) ─────────────")
    for name, bel, phase, status in threads:
        print(f"  │  {name} · Belief {bel} · {phase}")
        if status:
            print(f"  │    status: {status[:80]}")
    print("  │")
    print('  │  Add "thread_updates": [...] to events JSON to apply changes automatically.')
    print_narrative_obligations_for_closeout()
    seeds = []
    queue_path = BASE / "memory" / "tick-queue.md"
    if queue_path.exists():
        for line in queue_path.read_text(encoding="utf-8", errors="ignore").splitlines():
            m = re.search(r"\[THREAD SEED:\s*([^\]]+)\]", line)
            if m and m.group(1).strip() not in seeds:
                seeds.append(m.group(1).strip())
    if seeds:
        print("  │")
        print("  │  Emerging seeds waiting for confirmation:")
        for seed in seeds[-6:]:
            print(f"  │    · {seed}")
        print('  │  If one became real in play, add "new_threads": [...] to events JSON.')
    print("  └────────────────────────────────────────────────────────────────────────────")


def _load_narrative_steward_state() -> dict:
    if not NARRATIVE_STEWARD_STATE.exists():
        return {}
    try:
        return json.loads(NARRATIVE_STEWARD_STATE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _save_narrative_steward_state(state: dict):
    if not state:
        return
    if not NARRATIVE_STEWARD_STATE.parent.exists():
        NARRATIVE_STEWARD_STATE.parent.mkdir(parents=True, exist_ok=True)
    tmp = NARRATIVE_STEWARD_STATE.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    tmp.replace(NARRATIVE_STEWARD_STATE)


def print_narrative_obligations_for_closeout():
    state = _load_narrative_steward_state()
    obligations = [item for item in state.get("obligations", []) if item.get("status", "open") == "open"]
    if not obligations:
        return
    print("  │")
    print("  │  Narrative stewardship obligations:")
    for item in obligations[:5]:
        print(f"  │    · {item.get('severity', 'WATCH')} {item.get('title', '')}")
    print('  │  Satisfy with "thread_updates" / "new_threads", or explicitly defer in the scene.')


def resolve_narrative_obligations(events: dict, dry_run: bool):
    state = _load_narrative_steward_state()
    obligations = state.get("obligations", [])
    if not obligations:
        return
    thread_updates = events.get("thread_updates") or []
    new_threads = events.get("new_threads") or []
    touched_threads = {item.get("name", "").strip().lower() for item in thread_updates if item.get("name")}
    now = datetime.now(LOCAL_TZ).isoformat(timespec="seconds")
    changed = False

    for item in obligations:
        if item.get("status", "open") != "open":
            continue
        resolved_reason = ""
        kind = item.get("kind")
        if kind == "thread_beat_due" and item.get("thread", "").strip().lower() in touched_threads:
            resolved_reason = "closeout thread_updates supplied"
        elif kind == "seed_triage_due" and new_threads:
            resolved_reason = "closeout new_threads supplied"
        elif kind == "memory_refresh_due" and events.get("most_alive_moment"):
            resolved_reason = "closeout most_alive_moment supplied"
        elif kind == "drama_budget_guard":
            # The guard is satisfied by completing a normal closeout while the
            # scene contract remains in force; it will reopen if health still sees skew.
            resolved_reason = "session closeout completed under current scene contract"

        if resolved_reason:
            item["status"] = "resolved"
            item["resolved_at"] = now
            item["resolved_reason"] = resolved_reason
            changed = True
            print(f"  · Narrative obligation resolved: {item.get('title', item.get('id'))}")

    if changed and not dry_run:
        _save_narrative_steward_state(state)


def apply_thread_updates(thread_updates: list, dry_run: bool):
    """Apply thread_updates list from events JSON to world-register and threads.md."""
    for upd in thread_updates:
        name      = upd.get("name", "").strip()
        phase     = upd.get("phase", "").strip().lower()
        status    = upd.get("status", "").strip()
        next_beat = upd.get("next_beat", "").strip()

        if not name or not phase or not status:
            print(f"  · Skipping incomplete thread update: {upd}")
            continue

        print(f"  · Updating thread: {name} → {phase}")
        update_thread_in_register(name, phase, status, dry_run)
        update_thread_in_threads_md(name, phase, next_beat, dry_run)


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def apply_new_threads(new_threads: list, dry_run: bool):
    """Create newly confirmed thread sections and Active Threads rows."""
    if not new_threads:
        return

    threads_text = read_file(THREADS_MD)
    register_text = read_file(REGISTER_MD)
    today = datetime.now(LOCAL_TZ).strftime("%Y-%m-%d")
    thread_sections = []
    register_rows = []

    for item in new_threads:
        name = item.get("name", "").strip()
        thread_id = item.get("id", "").strip() or _slug(name)
        if not name:
            continue
        if f"## Thread: {name}" in threads_text or f"[id:{thread_id}]" in register_text:
            print(f"  · New thread already exists, skipping: {name}")
            continue

        phase = item.get("phase", "setup").strip().lower()
        pressure = item.get("pressure", "low").strip()
        thread_type = item.get("type", "npc-subplot").strip()
        npc_anchor = item.get("npc_anchor", "").strip()
        locations = item.get("locations", "unknown").strip()
        entities = item.get("entities", npc_anchor or name).strip()
        nothing_pressure = item.get("nothing_pressure", "medium - the Nothing can flatten this into absence.").strip()
        status = item.get("status", "").strip()
        next_beat = item.get("next_beat", "").strip()
        belief = int(item.get("starting_belief", 7))

        thread_sections.append(
            "\n"
            f"## Thread: {name}\n\n"
            f"**id:** `{thread_id}`\n"
            f"**type:** {thread_type}\n"
            f"**phase:** {phase}\n"
            f"**pressure:** {pressure}\n"
            f"**npc_anchor:** {npc_anchor}\n"
            f"**locations:** {locations}\n"
            f"**entities:** {entities}\n"
            f"**Nothing pressure:** {nothing_pressure}\n\n"
            f"**Next beat:** {next_beat}\n\n"
            f"**Last advanced:** {today}\n"
            f"**born:** {today}\n"
            "**closed:** —\n"
        )
        register_rows.append(f"| {name} | Thread | {belief} | [id:{thread_id}] Phase: {phase} — {status} |")
        print(f"  · New thread: {name} ({phase}, Belief {belief})")

    if not thread_sections and not register_rows:
        return

    if dry_run:
        print(f"  [dry-run] Would create {len(thread_sections)} new thread(s)")
        return

    if thread_sections:
        archive_marker = "\n## Archive"
        if archive_marker in threads_text:
            threads_text = threads_text.replace(archive_marker, "\n".join(thread_sections) + "\n" + archive_marker, 1)
        else:
            threads_text = threads_text.rstrip() + "\n" + "\n".join(thread_sections) + "\n"
        THREADS_MD.write_text(threads_text, encoding="utf-8")

    if register_rows:
        active_m = re.search(
            r"(^## Active Threads\s*\n\| Entity \| Type \| Belief \| Notes \|\n\|[-| ]+\|\n)",
            register_text,
            re.MULTILINE,
        )
        if active_m:
            register_text = register_text[: active_m.end()] + "\n".join(register_rows) + "\n" + register_text[active_m.end():]
            REGISTER_MD.write_text(register_text, encoding="utf-8")
        else:
            print("  · Could not find world-register Active Threads table; thread sections were written only.")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Close session — capture and cascade game state")
    parser.add_argument("--player",         default="bj",  help="Player name")
    parser.add_argument("--date",           default=None,  help="Target date (YYYY-MM-DD, default: today)")
    parser.add_argument("--session-file",   default=None,  help="Explicit session JSONL path (bypasses sessions.json lookup)")
    parser.add_argument("--events-file",    default=None,  help="Path to pre-generated events JSON (from the Labyrinth itself)")
    parser.add_argument("--dry-run",        action="store_true", help="Build transcript and extract, but don't write files")
    parser.add_argument("--transcript-only",action="store_true", help="Build and save transcript only — skip event extraction")
    parser.add_argument("--validate-only",  action="store_true", help="Validate --events-file and exit before writing state")
    args = parser.parse_args()

    date = args.date or datetime.now(LOCAL_TZ).strftime("%Y-%m-%d")
    ledger = scene_ledger_digest(date)
    print(f"\n📖 Closing session for {args.player} on {date}")

    if args.validate_only and args.events_file:
        ef = Path(args.events_file)
        if not ef.exists():
            print(f"  ✗ Events file not found: {ef}")
            sys.exit(1)
        try:
            events = json.loads(ef.read_text())
        except json.JSONDecodeError as e:
            print(f"  ✗ Could not parse events file: {e}")
            sys.exit(1)
        event_problems = validate_events(events)
        if event_problems:
            print("  ✗ Events JSON failed validation:")
            for problem in event_problems:
                print(f"    - {problem}")
            sys.exit(1)
        print("  ✓ Events JSON validated")
        print("\nDone (events validation only).")
        return

    # ── Step 1: Build transcript ──
    print("\n1. Collecting session messages…")
    if args.session_file:
        # Explicit file: extract all messages from it, regardless of date
        sf = Path(args.session_file)
        if not sf.exists():
            print(f"  ✗ Session file not found: {sf}")
            sys.exit(1)
        raw_msgs = load_session_messages(sf)
        # Still filter to target date (the session may span days)
        target = datetime.strptime(date, "%Y-%m-%d").date()
        messages = [m for m in raw_msgs if m["ts"].astimezone(LOCAL_TZ).date() == target]
        if not messages:
            # Fallback: use ALL messages from the file if none match the date
            messages = raw_msgs
        messages.sort(key=lambda m: m["ts"])
    else:
        messages = build_daily_transcript(date)

    if not messages:
        print(f"  ✗ No narrative messages found for {date}.")
        print("  (Check that sessions.json points to the right session files.)")
        sys.exit(1)

    print(f"  Found {len(messages)} messages ({sum(1 for m in messages if m['role']=='player')} player, "
          f"{sum(1 for m in messages if m['role']=='labyrinth')} labyrinth)")

    transcript_text = format_transcript(messages, date)
    transcript_path = BASE / "logs" / "transcripts" / f"{date}.md"

    # Append if a partial transcript was already saved today
    if transcript_path.exists() and not args.dry_run:
        existing = transcript_path.read_text()
        # Merge: keep existing, add new messages not already present
        transcript_path.write_text(transcript_text)
        print(f"  ✓ Transcript updated → {transcript_path.relative_to(BASE)}")
    else:
        if not args.dry_run:
            transcript_path.parent.mkdir(parents=True, exist_ok=True)
            transcript_path.write_text(transcript_text)
            print(f"  ✓ Transcript saved → {transcript_path.relative_to(BASE)}")
        else:
            print(f"  [dry-run] Transcript ready ({len(transcript_text)} chars)")

    if args.transcript_only:
        print("\nDone (transcript only).")
        return

    # ── Step 2: Load or extract structured events ──
    print("\n2. Loading structured events…")
    events = None

    if args.events_file:
        ef = Path(args.events_file)
        if not ef.exists():
            print(f"  ✗ Events file not found: {ef}")
            sys.exit(1)
        try:
            events = json.loads(ef.read_text())
            print(f"  ✓ Loaded events from {ef.name}")
        except json.JSONDecodeError as e:
            print(f"  ✗ Could not parse events file: {e}")
            sys.exit(1)
    else:
        print("  → No events file provided; calling Openclaw agent for extraction…")
        print("    (Note: this fails if called from within a running session due to lock.)")
        print("    (Preferred usage: --events-file /tmp/enchantify-events.json)")
        events = extract_events(transcript_text, date, args.player)

    if not events:
        print("  ✗ Event extraction failed. Transcript saved; state files unchanged.")
        sys.exit(1)

    event_problems = validate_events(events)
    if event_problems:
        print("  ✗ Events JSON failed validation:")
        for problem in event_problems:
            print(f"    - {problem}")
        sys.exit(1)
    print("  ✓ Events JSON validated")

    if args.validate_only:
        print("\nDone (events validation only).")
        return

    # Print a summary of what was found
    def show(label, val):
        if val and val != "null":
            print(f"  · {label}: {str(val)[:100]}")

    show("Belief final",     events.get("belief_final"))
    show("Belief changes",   events.get("belief_changes"))
    show("Investments",      events.get("belief_investments"))
    show("Nothing events",   events.get("nothing_events"))
    show("Enchantments",     events.get("enchantments_cast"))
    show("NPC interactions", events.get("npc_interactions"))
    show("Summary",          events.get("session_summary"))
    if ledger["titles"]:
        show("Scene ledger", ", ".join(ledger["titles"][-3:]))
    if ledger["delivery_failures"]:
        show("Delivery issues", ledger["delivery_failures"])

    # Save raw extracted JSON alongside transcript for debugging
    events_path = BASE / "logs" / "transcripts" / f"{date}-events.json"
    if not args.dry_run:
        events_path.write_text(json.dumps(events, indent=2, ensure_ascii=False))
        print(f"  ✓ Events JSON saved → {events_path.relative_to(BASE)}")

    if ledger["entries"]:
        events["scene_ledger"] = {
            "scene_ids": ledger["scene_ids"],
            "titles": ledger["titles"],
            "delivery_failures": ledger["delivery_failures"],
            "latest_text": ledger["latest_text"][:1000],
        }

    # ── Step 3: Cascade to state files ──
    print("\n3. Updating state files…")
    update_diary(events, date, args.player, args.dry_run)
    update_arc_spine(events, date, args.dry_run)
    update_nothing_intelligence(events, date, args.dry_run)
    update_player_file(events, args.player, args.dry_run)
    update_labyrinth_state_from_events(events, args.dry_run)

    # ── Step 4: Thread updates ──
    new_threads = events.get("new_threads", [])
    if new_threads:
        print("\n4. Creating new story threads…")
        apply_new_threads(new_threads, args.dry_run)

    thread_updates = events.get("thread_updates", [])
    if thread_updates:
        print("\n4. Updating thread state…")
        apply_thread_updates(thread_updates, args.dry_run)
    elif not new_threads:
        print_thread_checklist()
    resolve_narrative_obligations(events, args.dry_run)

    # ── Step 5: Earning ──
    compass_runs  = events.get("compass_runs_completed", 0) or 0
    enchantments  = len(events.get("enchantments_cast",  []) or [])
    earn_total    = 0.0
    earn_args     = []

    earn_args.append((0.50, "Session completed"))
    if compass_runs:
        earn_args.append((compass_runs * 2.00, f"Compass Run{'s' if compass_runs > 1 else ''} ×{compass_runs}"))
    if enchantments:
        earn_args.append((enchantments * 1.00, f"Enchantment{'s' if enchantments > 1 else ''} ×{enchantments}"))

    if earn_args:
        print("\n5. Crediting spend balance…")
        spend_script = BASE / "scripts" / "spend.py"
        for amount, reason in earn_args:
            earn_total += amount
            cmd = [sys.executable, str(spend_script), "--earn", str(amount), reason]
            if args.dry_run:
                cmd.append("--dry-run")
            subprocess.run(cmd, capture_output=False)

    print(f"\n✅ Session closed for {date}.\n")


if __name__ == "__main__":
    main()
