#!/usr/bin/env python3
"""
close-session.py — End-of-session state capture.

1. Reads today's game session JSONL(s) for the player's Telegram channel
2. Extracts narrative exchanges (player + Labyrinth), filters out cron/system noise
3. Saves a clean daily transcript to logs/transcripts/YYYY-MM-DD.md
4. Loads structured events — either from --events-file (preferred, generated by the
   Labyrinth itself) or by calling the default Openclaw agent on the transcript
5. Cascades those events to state files:
     - memory/diary/YYYY-MM-DD.md     (appends session summary if not already written)
     - memory/arc-spine.md            (last session, what story is ready for)
     - lore/nothing-intelligence.md   (pressure, confrontations, strategy update)
     - players/[name].md              (belief, investments, inventory, relationships)

## How the Labyrinth should call this

The Labyrinth runs this at session close, from within the running session. Because the
session is locked, it cannot call `openclaw agent --local` for extraction. Instead,
the Labyrinth generates the events JSON itself and passes it in:

  1. Labyrinth generates a JSON object matching the schema below
  2. Writes it to /tmp/enchantify-events.json
  3. Calls: python3 scripts/close-session.py --player bj \\
               --session-file ~/.openclaw/agents/enchantify/sessions/<current>.jsonl \\
               --events-file /tmp/enchantify-events.json

## Events JSON schema

{
  "belief_final": 81,                  // player Belief at session end, or null
  "belief_changes": [                  // every Belief gain/loss
    {"amount": 3, "reason": "..."}
  ],
  "belief_investments": [              // Belief permanently invested somewhere
    {"target": "Zara Finch", "type": "npc", "amount": 10, "notes": "..."}
  ],
  "nothing_events": [                  // confrontations, manifestations, retreats
    {"type": "confrontation", "date": "2026-04-17",
     "location": "North Gardens", "outcome": "overwritten", "details": "..."}
  ],
  "enchantments_cast": [
    {"name": "Everything Speaks", "target": "table lager", "outcome": "..."}
  ],
  "npc_interactions": [                // only if relationship score changed
    {"npc": "Zara Finch", "relationship_delta": 5, "notes": "..."}
  ],
  "inventory_changes": [
    {"action": "gained", "item": "black envelope", "notes": "left by Nothing"}
  ],
  "fae_bargains": [],
  "quests_completed": [],
  "quests_added": [],
  "session_summary": "...",            // 2-3 sentence narrative summary
  "most_alive_moment": "...",          // most vivid real moment
  "what_fell_flat": null               // or string
}

## Standalone usage (no running session, --events-file not needed)

  python3 scripts/close-session.py                            # today, auto-detect session
  python3 scripts/close-session.py --player bj --date 2026-04-17
  python3 scripts/close-session.py --session-file /path/to/session.jsonl
  python3 scripts/close-session.py --transcript-only         # transcript only, no events
  python3 scripts/close-session.py --dry-run                 # no file writes
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

BASE        = Path(__file__).parent.parent
SESSIONS_F  = Path.home() / ".openclaw" / "agents" / "enchantify" / "sessions" / "sessions.json"
SESSIONS_D  = SESSIONS_F.parent
OPENCLAW_BIN = shutil.which("openclaw") or "/opt/homebrew/bin/openclaw" or "/usr/local/bin/openclaw"

# Local timezone — used for grouping messages by "day"
LOCAL_TZ = ZoneInfo("America/New_York")

# Channel keys that represent actual player game sessions (not cron, not openai test)
PLAYER_CHANNEL_PATTERNS = [
    "agent:enchantify:telegram:direct:",
    "agent:enchantify:main",
]


# ── Parsing helpers ────────────────────────────────────────────────────────────

def parse_player_text(raw: str):
    """
    Extract the actual player-typed text from a user message.

    Player messages from Telegram come wrapped in a 'Conversation info' JSON block.
    Bare messages (from /slash commands or direct injection) are returned as-is
    after filtering out system-only content.
    Returns str or None.
    """
    if raw.startswith("System:"):
        return None
    if raw.startswith("[cron:"):
        return None
    if raw.startswith("--- SESSION ENTRY"):
        return None

    # Telegram wrapper: "Conversation info (untrusted metadata):\n```json\n...\n```\n\nSender...\n\nACTUAL TEXT"
    m = re.search(r'Sender \(untrusted[^\n]*\)\s*\n+(.*)', raw, re.DOTALL)
    if m:
        text = m.group(1).strip()
        if not text or text.startswith("[plugins]"):
            return None
        return text

    # Media-only message with no text
    if raw.startswith("[media attached:") and "\n" not in raw.strip():
        return "[image shared]"

    # Bare message (no Telegram wrapper) — only accept if short and not a system prompt
    stripped = raw.strip()
    system_prefixes = (
        "You are the Labyrinth", "HEARTBEAT", "---\n", "Context about",
        "--- SESSION", "DIRECTIVE:", "[cron", "System:", "# Tick",
        "PLAYER:", "AWAY_HOURS:", "TODAY:", "BASE PATH:",
    )
    if any(stripped.startswith(p) for p in system_prefixes):
        return None
    if len(stripped) > 300:
        return None
    if len(stripped) < 2:
        return None
    return stripped


def parse_labyrinth_text(content):
    """Extract the visible narrative text from an assistant message."""
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        parts = []
        for c in content:
            if isinstance(c, dict) and c.get("type") == "text":
                parts.append(c["text"])
        text = "\n".join(parts)
    else:
        return None

    # Strip <think>...</think> blocks (internal reasoning)
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

    # Unwrap <final>...</final>
    m = re.search(r'<final>(.*?)</final>', text, re.DOTALL)
    if m:
        text = m.group(1).strip()

    # Filter pure system messages
    if text.startswith("✅ New session started"):
        return None
    if text == "NO_REPLY" or not text:
        return None
    if len(text) < 10:
        return None

    return text


def load_session_messages(session_file: Path) -> list[dict]:
    """Parse a JSONL session file, return list of {ts, role, text} dicts."""
    messages = []
    if not session_file.exists():
        return messages

    with open(session_file) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            if obj.get("type") != "message":
                continue

            msg   = obj.get("message", {})
            role  = msg.get("role", "")
            ts_s  = obj.get("timestamp", "")
            content = msg.get("content", "")

            if not role or not ts_s:
                continue

            try:
                ts = datetime.fromisoformat(ts_s.replace("Z", "+00:00"))
            except ValueError:
                continue

            if role == "user":
                raw = content[0]["text"] if isinstance(content, list) and content else str(content)
                text = parse_player_text(raw)
                if text:
                    messages.append({"ts": ts, "role": "player", "text": text})

            elif role == "assistant":
                text = parse_labyrinth_text(content)
                if text:
                    messages.append({"ts": ts, "role": "labyrinth", "text": text})

    return messages


def find_player_session_files() -> list[Path]:
    """Return session file paths for all player-facing channels, most recent first."""
    if not SESSIONS_F.exists():
        return []

    with open(SESSIONS_F) as f:
        sessions = json.load(f)

    files = []
    for key, val in sessions.items():
        if any(key.startswith(p) for p in PLAYER_CHANNEL_PATTERNS):
            sf = val.get("sessionFile", "")
            if sf:
                p = Path(sf)
                if p.exists():
                    files.append(p)

    # Deduplicate, sort newest first by mtime
    seen = set()
    unique = []
    for p in sorted(set(files), key=lambda x: x.stat().st_mtime, reverse=True):
        if p not in seen:
            seen.add(p)
            unique.append(p)

    return unique


def build_daily_transcript(target_date: str) -> list[dict]:
    """
    Collect all narrative messages from target_date (YYYY-MM-DD, local time).
    Searches across session files — a single session can span midnight.
    """
    target = datetime.strptime(target_date, "%Y-%m-%d").date()
    all_messages = []

    session_files = find_player_session_files()
    # Also scan recent session files that aren't indexed (e.g. after context reset)
    for p in sorted(SESSIONS_D.glob("*.jsonl"), key=lambda x: x.stat().st_mtime, reverse=True)[:20]:
        if p not in session_files:
            session_files.append(p)

    seen_texts = set()
    for sf in session_files:
        for msg in load_session_messages(sf):
            local_date = msg["ts"].astimezone(LOCAL_TZ).date()
            if local_date == target:
                key = (msg["role"], msg["text"][:80])
                if key not in seen_texts:
                    seen_texts.add(key)
                    all_messages.append(msg)

    all_messages.sort(key=lambda m: m["ts"])
    return all_messages


def format_transcript(messages: list[dict], date: str) -> str:
    """Render messages as a readable markdown transcript."""
    lines = [f"# Session Transcript — {date}\n"]
    prev_date = None

    for msg in messages:
        local_ts = msg["ts"].astimezone(LOCAL_TZ)
        day_str = local_ts.strftime("%A, %B %-d")
        if day_str != prev_date:
            lines.append(f"\n---\n*{day_str}*\n")
            prev_date = day_str

        time_str = local_ts.strftime("%-I:%M %p")
        label = "**bj**" if msg["role"] == "player" else "*The Labyrinth*"
        text = msg["text"].strip()
        lines.append(f"[{time_str}] {label}: {text}\n")

    return "\n".join(lines)


# ── LLM extraction ─────────────────────────────────────────────────────────────

EXTRACTION_PROMPT_TEMPLATE = """You are the Enchantify state-capture system. Read the session transcript below and extract structured events.

Return ONLY a valid JSON object — no markdown, no commentary, no code block. If a field has nothing to report, use an empty array or null.

Extract:
- belief_final: the player's Belief score at session end (integer, or null if unclear)
- belief_changes: list of {{amount, reason}} — every Belief gain/loss mentioned
- belief_investments: list of {{target, type, amount, notes}} where type is "anchor", "npc", "location", or "object"
- nothing_events: list of {{type, date, location, outcome, details}} — confrontations, manifestations, retreats
- enchantments_cast: list of {{name, target, outcome}}
- npc_interactions: list of {{npc, relationship_delta, notes}} — only if relationship changed
- inventory_changes: list of {{action, item, notes}} where action is "gained" or "lost"
- fae_bargains: list of {{fae, gave, owes, deadline}}
- quests_completed: list of quest NPC names
- quests_added: list of {{npc, description}}
- session_summary: 2-3 sentence summary of what happened narratively
- most_alive_moment: the single most vivid/real moment from the session (quoted or described)
- what_fell_flat: anything that felt mechanical, flat, or broke immersion (or null)
- notable_objects: any objects that appeared, changed, or were left behind (the black envelope, etc.)

SESSION DATE: {date}
PLAYER: {player}

TRANSCRIPT:
{transcript}"""


def call_openclaw(prompt: str, timeout: int = 180) -> str:
    """Call the default Openclaw agent and return its text output."""
    result = subprocess.run(
        [OPENCLAW_BIN, "agent", "--local", "--agent", "enchantify", "-m", prompt],
        capture_output=True, text=True, timeout=timeout
    )
    output = result.stdout.strip()
    # Strip ANSI escape codes and noise lines
    output = re.sub(r'\x1b\[[0-9;]*m', '', output)
    noise = ("[plugins]", "[agents/", "[agent/", "adopted ", "google tool", "✅ New session")
    clean = [line for line in output.splitlines() if not any(line.strip().startswith(n) for n in noise)]
    return "\n".join(clean).strip()


def extract_events(transcript_text: str, date: str, player: str):
    """Send transcript to the default agent and parse structured event JSON."""
    # Trim transcript if very long — keep first + last portions for context
    max_chars = 12000
    if len(transcript_text) > max_chars:
        half = max_chars // 2
        transcript_text = transcript_text[:half] + "\n\n[... middle trimmed for length ...]\n\n" + transcript_text[-half:]

    prompt = EXTRACTION_PROMPT_TEMPLATE.format(
        date=date, player=player, transcript=transcript_text
    )

    print("  → Calling default Openclaw agent for event extraction…")
    raw = call_openclaw(prompt)

    # Find JSON in the response
    json_match = re.search(r'\{.*\}', raw, re.DOTALL)
    if not json_match:
        print(f"  ✗ No JSON found in agent response. Raw output:\n{raw[:500]}")
        return None

    try:
        return json.loads(json_match.group(0))
    except json.JSONDecodeError as e:
        print(f"  ✗ JSON parse error: {e}\nRaw: {raw[:500]}")
        return None


# ── State file updaters ──────��─────────────────────────────────────────────────

def read_file(path: Path) -> str:
    return path.read_text() if path.exists() else ""


def write_file(path: Path, content: str, dry_run: bool = False):
    if dry_run:
        print(f"  [dry-run] Would write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  ✓ Updated {path.relative_to(BASE)}")


def update_diary(events: dict, date: str, player: str, dry_run: bool):
    diary_path = BASE / "memory" / "diary" / f"{date}.md"
    summary = events.get("session_summary", "").strip()
    alive   = events.get("most_alive_moment", "").strip()
    flat    = events.get("what_fell_flat", "")

    if not summary:
        return

    existing = read_file(diary_path)

    # Don't duplicate if summary already appears in the file
    if summary[:60] in existing:
        print(f"  · Diary already contains today's summary — skipping")
        return

    entry_parts = [f"## Session {date}\n", summary]
    if alive:
        entry_parts.append(f"\n*Most alive:* {alive}")
    if flat and flat.lower() not in ("null", "none", ""):
        entry_parts.append(f"\n*What fell flat:* {flat}")

    entry = "\n".join(entry_parts)

    if existing.strip():
        new_content = existing.rstrip() + "\n\n---\n\n" + entry + "\n"
    else:
        new_content = f"# Labyrinth Diary — {date}\n*Player: {player}*\n\n" + entry + "\n"

    write_file(diary_path, new_content, dry_run)


def update_arc_spine(events: dict, date: str, dry_run: bool):
    spine_path = BASE / "memory" / "arc-spine.md"
    content = read_file(spine_path)
    summary = events.get("session_summary", "").strip()

    if not summary:
        return

    # Update belief state line if we have a final belief
    belief_final = events.get("belief_final")
    if belief_final and isinstance(belief_final, int):
        content = re.sub(
            r'(- Belief:\s*)\d+(\s*[—-])',
            lambda m: f"{m.group(1)}{belief_final}{m.group(2)}",
            content
        )

    # Replace Last Session block
    new_session_block = f"## Last Session\n*{date}*\n\n{summary[:400]}"
    if re.search(r'^## Last Session', content, re.MULTILINE):
        content = re.sub(
            r'## Last Session\s*\n.*?(?=\n##|\Z)',
            new_session_block + "\n",
            content,
            flags=re.DOTALL
        )
    else:
        content = content.rstrip() + "\n\n" + new_session_block + "\n"

    write_file(spine_path, content, dry_run)


def update_nothing_intelligence(events: dict, date: str, dry_run: bool):
    path = BASE / "lore" / "nothing-intelligence.md"
    content = read_file(path)
    nothing_events = events.get("nothing_events", [])
    if not nothing_events:
        return

    confrontations = [e for e in nothing_events if e.get("type") in ("confrontation", "overwrite", "defeat")]
    if not confrontations:
        return

    c = confrontations[-1]
    event_date     = c.get("date", date)
    location       = c.get("location", "unknown location")
    outcome        = c.get("outcome", "outcome unknown")
    details        = c.get("details", "")

    # Update pressure level
    content = re.sub(r'(Pressure level:\s*).*', r'\1retreating', content)

    # Update Updated date
    content = re.sub(r'(\*Updated:\s*)[\d-]+', rf'\g<1>{date}', content)

    # Append to Recent Activity
    new_activity = f"- **{event_date}:** {details or f'Confronted and {outcome} at {location}. Retreated.'}"
    if "## Recent Nothing Activity" in content:
        content = content.rstrip() + f"\n{new_activity}\n"
    else:
        content += f"\n\n## Recent Nothing Activity (from diary)\n{new_activity}\n"

    write_file(path, content, dry_run)


def update_player_file(events: dict, player: str, dry_run: bool):
    path = BASE / "players" / f"{player}.md"
    content = read_file(path)

    # Update Belief score
    belief_final = events.get("belief_final")
    if belief_final and isinstance(belief_final, int):
        content = re.sub(
            r'(- \*\*Belief:\*\*\s*)\d+',
            rf'\g<1>{belief_final}',
            content
        )

    # Add new Belief investments to the table
    investments = events.get("belief_investments", [])
    for inv in investments:
        target = inv.get("target", "?")
        inv_type = inv.get("type", "?")
        amount = inv.get("amount", "TBC")
        notes = inv.get("notes", "")

        # Check if already in the table
        if target.lower() in content.lower() and "Belief Investments" in content:
            continue

        new_row = f"| {target} | {inv_type.title()} | {amount} | {notes} |"

        if re.search(r'## Belief Investments\s*\n\s*\|', content):
            # Append to existing table
            content = re.sub(
                r'(## Belief Investments\s*\n(?:\|[^\n]+\n)+)',
                lambda m: m.group(0).rstrip() + f"\n{new_row}\n",
                content
            )
        else:
            # Replace the empty placeholder
            new_table = (
                "## Belief Investments\n\n"
                "| Target | Type | Belief | Notes |\n"
                "|---|---|---|---|\n"
                f"{new_row}\n"
            )
            content = re.sub(
                r'## Belief Investments\s*\n\n\*\(Nothing invested.*?\)\*',
                new_table.rstrip(),
                content,
                flags=re.DOTALL
            )

    # Update relationship scores
    for interaction in events.get("npc_interactions", []):
        npc   = interaction.get("npc", "")
        delta = interaction.get("relationship_delta", 0)
        if not npc or not delta:
            continue
        # Find existing row in Relationships table
        m = re.search(
            rf'(\|\s*{re.escape(npc)}\s*\|[^|]*\|\s*)(\d+)(\s*\|)',
            content
        )
        if m:
            new_score = int(m.group(2)) + int(delta)
            content = content[:m.start()] + m.group(1) + str(new_score) + m.group(3) + content[m.end():]

    write_file(path, content, dry_run)


# ── Main ───────────────────────────────���───────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Close session — capture and cascade game state")
    parser.add_argument("--player",         default="bj",  help="Player name")
    parser.add_argument("--date",           default=None,  help="Target date (YYYY-MM-DD, default: today)")
    parser.add_argument("--session-file",   default=None,  help="Explicit session JSONL path (bypasses sessions.json lookup)")
    parser.add_argument("--events-file",    default=None,  help="Path to pre-generated events JSON (from the Labyrinth itself)")
    parser.add_argument("--dry-run",        action="store_true", help="Build transcript and extract, but don't write files")
    parser.add_argument("--transcript-only",action="store_true", help="Build and save transcript only — skip event extraction")
    args = parser.parse_args()

    date = args.date or datetime.now(LOCAL_TZ).strftime("%Y-%m-%d")
    print(f"\n📖 Closing session for {args.player} on {date}")

    # ── Step 1: Build transcript ──
    print("\n1. Collecting session messages…")
    if args.session_file:
        # Explicit file: extract all messages from it, regardless of date
        sf = Path(args.session_file)
        if not sf.exists():
            print(f"  ✗ Session file not found: {sf}")
            sys.exit(1)
        raw_msgs = load_session_messages(sf)
        # Still filter to target date (the session may span days)
        target = datetime.strptime(date, "%Y-%m-%d").date()
        messages = [m for m in raw_msgs if m["ts"].astimezone(LOCAL_TZ).date() == target]
        if not messages:
            # Fallback: use ALL messages from the file if none match the date
            messages = raw_msgs
        messages.sort(key=lambda m: m["ts"])
    else:
        messages = build_daily_transcript(date)

    if not messages:
        print(f"  ✗ No narrative messages found for {date}.")
        print("  (Check that sessions.json points to the right session files.)")
        sys.exit(1)

    print(f"  Found {len(messages)} messages ({sum(1 for m in messages if m['role']=='player')} player, "
          f"{sum(1 for m in messages if m['role']=='labyrinth')} labyrinth)")

    transcript_text = format_transcript(messages, date)
    transcript_path = BASE / "logs" / "transcripts" / f"{date}.md"

    # Append if a partial transcript was already saved today
    if transcript_path.exists() and not args.dry_run:
        existing = transcript_path.read_text()
        # Merge: keep existing, add new messages not already present
        transcript_path.write_text(transcript_text)
        print(f"  ✓ Transcript updated → {transcript_path.relative_to(BASE)}")
    else:
        if not args.dry_run:
            transcript_path.parent.mkdir(parents=True, exist_ok=True)
            transcript_path.write_text(transcript_text)
            print(f"  ✓ Transcript saved → {transcript_path.relative_to(BASE)}")
        else:
            print(f"  [dry-run] Transcript ready ({len(transcript_text)} chars)")

    if args.transcript_only:
        print("\nDone (transcript only).")
        return

    # ── Step 2: Load or extract structured events ──
    print("\n2. Loading structured events…")
    events = None

    if args.events_file:
        ef = Path(args.events_file)
        if not ef.exists():
            print(f"  ✗ Events file not found: {ef}")
            sys.exit(1)
        try:
            events = json.loads(ef.read_text())
            print(f"  ✓ Loaded events from {ef.name}")
        except json.JSONDecodeError as e:
            print(f"  ✗ Could not parse events file: {e}")
            sys.exit(1)
    else:
        print("  → No events file provided; calling Openclaw agent for extraction…")
        print("    (Note: this fails if called from within a running session due to lock.)")
        print("    (Preferred usage: --events-file /tmp/enchantify-events.json)")
        events = extract_events(transcript_text, date, args.player)

    if not events:
        print("  ✗ Event extraction failed. Transcript saved; state files unchanged.")
        sys.exit(1)

    # Print a summary of what was found
    def show(label, val):
        if val and val != "null":
            print(f"  · {label}: {str(val)[:100]}")

    show("Belief final",     events.get("belief_final"))
    show("Belief changes",   events.get("belief_changes"))
    show("Investments",      events.get("belief_investments"))
    show("Nothing events",   events.get("nothing_events"))
    show("Enchantments",     events.get("enchantments_cast"))
    show("NPC interactions", events.get("npc_interactions"))
    show("Summary",          events.get("session_summary"))

    # Save raw extracted JSON alongside transcript for debugging
    events_path = BASE / "logs" / "transcripts" / f"{date}-events.json"
    if not args.dry_run:
        events_path.write_text(json.dumps(events, indent=2, ensure_ascii=False))
        print(f"  ✓ Events JSON saved → {events_path.relative_to(BASE)}")

    # ── Step 3: Cascade to state files ──
    print("\n3. Updating state files…")
    update_diary(events, date, args.player, args.dry_run)
    update_arc_spine(events, date, args.dry_run)
    update_nothing_intelligence(events, date, args.dry_run)
    update_player_file(events, args.player, args.dry_run)

    print(f"\n✅ Session closed for {date}.\n")


if __name__ == "__main__":
    main()
